# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Name: es
PeerPort: 2380
ClientPort: 2379
Component: "elasticsearch"
Image: "dmfenton/elasticsearch-pet"
ImageTag: "latest"
ImagePullPolicy: "Always"
ClientReplicas: 2
ClientCpuRequests: "25m"
ClientMemoryRequests: "1024Mi"
ClientCpuLimits: "1000m"
ClientMemoryLimits: "1024Mi"
ClientHeapSize: "512m"
MasterReplicas: 2
MasterCpuRequests: "25m"
MasterMemoryRequests: "1024Mi"
MasterCpuLimits: "1000m"
MasterMemoryLimits: "1024Mi"
MasterHeapSize: "512m"
DataReplicas: 3
DataCpuRequests: "250m"
DataMemoryRequests: "2Gi"
DataCpuLimits: "2000m"
DataMemoryLimits: "4Gi"
DataHeapSize: "1536m"
DataStorage: "30Gi"
DataStorageClass: "anything"
DataStorageClassVersion: "alpha"
